[package]
name = "upsc"
version = "0.1.0"
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
glam.workspace = true

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
upsc-ngx = { path = "../upsc-ngx", features = ["vulkan"] }

[build-dependencies]
cfg_aliases.workspace = true