[package]
name = "upsc"
version = "0.1.0"
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "A cross-platform upscaler for wgpu! 🚀"

[dependencies]
upsc-core = { git = "https://github.com/luc-rodriguez/upsc", package = "upsc-core" }