[package]
name = "upsc-core"
version = "0.1.0"
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "The consuming crate for various backends."

[dependencies]
glam.workspace = true

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
upsc-ngx = { git = "https://github.com/luc-rodriguez/upsc", package = "upsc-ngx", default-features = false, features = ["vulkan"] }
upsc-fidelityfx = { git = "https://github.com/luc-rodriguez/upsc", package = "upsc-fidelityfx", default-features = false, features = ["vulkan"]}

[build-dependencies]
cfg_aliases.workspace = true